title: Awesome Title will go here
author: Lauren Milburn
email: lom698@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  Description will go here

# social links
twitter_username: twitter_handle
github_username:  laurenmilburn

show_excerpts: false
